services:
  vision_cam_poc:
    container_name: vision-cam-poc
    build:
      context: .
      dockerfile: Dockerfile

    environment:
      # -------- Runtime / logs --------
      PYTHONUNBUFFERED: "1"

      # -------- Cámara --------
      CAM_INDEX: "0"          # prueba 0 o 1
      RESIZE_W: "224"
      RESIZE_H: "224"

      # -------- Trigger por movimiento --------
      MOTION_THRESHOLD: "25"
      MOTION_MIN_AREA: "1200"
      STABLE_MS: "800"

      # -------- Optimización CPU --------
      OMP_NUM_THREADS: "2"
      MKL_NUM_THREADS: "2"

      # -------- Modelo MobileNet --------
      MOBILENET_WEIGHTS: "/models/mobilenet/mobilenet_v3_small_imagenet.pth"

    volumes:
      - "./models/mobilenet:/models/mobilenet:ro"

    devices:
      - "/dev/video0:/dev/video0"
      - "/dev/video1:/dev/video1"

    group_add:
      - "video"

    restart: "no"
